/**
 * @fileOverview Action Type Enum
 * @author Max
 **/

const ACTION_TYPE = {
    LIST_REPORT: 'LIST_REPORT',
    DELETE_REPORT: 'DELETE_REPORT',
    SAVE_REPORT: 'SAVE_REPORT',
    GET_SINGLE_REPORT: 'GET_SINGLE_REPORT',
    UPDATE_REPORT: 'UPDATE_REPORT',
    LIST_TEACHER: 'LIST_TEACHER',
    DELETE_TEACHER: 'DELETE_TEACHER',
    SAVE_TEACHER: 'SAVE_TEACHER',
    GET_SINGLE_TEACHER: 'GET_SINGLE_TEACHER',
    UPDATE_TEACHER: 'UPDATE_TEACHER',
    USER_LOG_IN: 'USER_LOG_IN',
    USER_LOG_OUT: 'USER_LOG_OUT',
    GET_AD_CONFIG: 'GET_AD_CONFIG',
    UPDATE_AD_CONFIG: 'UPDATE_AD_CONFIG'
};


export default ACTION_TYPE;
